name: LINUX|TESTS
on:
  workflow_run:
    workflows: [LINUX|BUILD]
    branches: [main]
    types: [completed]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Get Event JSON
        id: get_event_json
        run: |
          content=`cat ${GITHUB_EVENT_PATH}`
          # the following lines are only required for multi line json
          # content="${content//'%'/''}"
          content="${content//$'\n'/''}"
          content="${content//$'\r'/''}"
          # end of optional handling for multi line json
          echo "value=${content}" >> ${GITHUB_OUTPUT}

      - name: Get run id
        id: get_run_id
        run: |
          echo "value="${{ fromJson(steps.get_event_json.outputs.value).workflow_run.id }} >> ${GITHUB_OUTPUT}

      - name: Get run artifact
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ steps.get_run_id.outputs.value }}
          name: build
          github-token: ${{ secrets.GH_PAT }}
 