name: LINUX|TESTS
on:
  workflow_run:
    workflows: [LINUX|BUILD]
    branches: [main]
    types: [completed]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - run: cat ${{ github.env.GITHUB_EVENT_PATH }}
