name: LINUX|TESTS
on:
  workflow_run:
    workflows: [LINUX|BUILD]
    branches: [main]
    types: [completed]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Get event json
        id: get_event_json
        run: |
          content=`cat ${GITHUB_EVENT_PATH}`
          content="${content//'%'/''}"
          content="${content//$'\n'/''}"
          content="${content//$'\r'/''}"
          echo "value=${content}" >> ${GITHUB_OUTPUT}

      - name: Get run id
        id: get_run_id
        run: |
          echo "value="${{ fromJson(steps.get_event_json.outputs.value).workflow_run.id }} >> ${GITHUB_OUTPUT}

      - name: Get run artifact
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ steps.get_run_id.outputs.value }}
          name: build
          path: .
          github-token: ${{ secrets.GH_PAT }}

      - name: Run Meson
        env:
          BOOST_ROOT: "${{ github.workspace }}/boost/boost"
        run: |
          pip install meson ninja
          meson test -C build -v
