name: LINUX|TESTS
on:
  workflow_run:
    workflows: [LINUX|BUILD]
    branches: [main]
    types: [completed]

  push:
    branches:
      - main
    paths:
      - '**.hpp'
      - '**.cpp'
      - 'meson.build'
      - '.github/workflows/linux_*.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: cat ${{ env.GITHUB_EVENT_PATH }}
