name: LINUX|TESTS
on:
  workflow_run:
    workflows: [LINUX|BUILD]
    branches: [main]
    types: [completed]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: cat ${{ env.GITHUB_EVENT_PATH }}
