name: LINUX|BUILD
on: 
  push:
    branches:
      - main
    paths:
      - '**.hpp'
      - '**.cpp'
      - 'meson.build'
      - '.github/workflows/linux_*.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Boost
        uses: MarkusJx/install-boost@v2
        with:
          boost_version: 1.87.0
          platform_version: 22.04
          toolset: gcc
          arch: x86

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Run Meson compile
        env:
          BOOST_ROOT: "${{ github.workspace }}/boost/boost"
        run: |
          pip install meson ninja
          mkdir install
          meson setup --backend=ninja build --prefix="$(pwd)/install"
          meson compile -C build -v
          meson install -C build

      - name: Tar build and meson build
        run: tar -zcvf install.tar.gz install

      - name: Upload build dir
        uses: actions/upload-artifact@v4
        with:
          name: install
          path: install.tar.gz
          if-no-files-found: error
          overwrite: true
          include-hidden-files: true
