name: LINUX|TESTS
on:
  workflow_run:
    workflows: [LINUX|BUILD]
    branches: [main]
    types: [completed]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ env.GITHUB_EVENT_PATH }}
          echo ${{ github.env.GITHUB_EVENT_PATH }}
          echo ${GITHUB_EVENT_PATH}
          cat ${{ env.GITHUB_EVENT_PATH }}
          cat ${{ github.env.GITHUB_EVENT_PATH }}
          cat ${GITHUB_EVENT_PATH}
