name: LINUX|TESTS
on:
  workflow_run:
    branches: main
    types: completed

  push:
    branches:
      - main
    paths:
      - '**.hpp'
      - '**.cpp'
      - 'meson.build'
      - '.github/workflows/linux_tests.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build
          github-token: ${{ secrets.GH_PATH }}
