name: MACOS|BUILD
permissions:
  contents: read
  actions: read
  checks: none
  deployments: none
  issues: none
  discussions: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on:
  push:
    branches:
      - main
    paths:
      - '**.hpp'
      - '**.cpp'
      - 'meson.build'
      - '.github/workflows/macos_*.yml'

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Boost
        uses: MarkusJx/install-boost@v2
        with:
          boost_version: 1.87.0
          platform_version: 15
          toolset: clang
          arch: aarch64

      - name: Install Clang
        run: |
          brew install llvm@20
          brew install lld@20

      - name: Install Meson and Ninja
        run: pip install meson ninja

      - name: Run Meson setup
        env:
          BOOST_ROOT: "${{ github.workspace }}/boost/boost"
          LDFLAGS: "-L/opt/homebrew/opt/llvm/lib -L/opt/homebrew/opt/llvm/lib/c++ -L/opt/homebrew/opt/llvm/lib/unwind -lunwind"
          CPPFLAGS: "-I/opt/homebrew/opt/llvm/include"
          CXX: "clang++"
          LD: "lld"
        run: PATH="/opt/homebrew/opt/llvm@20/bin:$PATH" meson setup --buildtype release --backend=ninja build --prefix="$(pwd)/install"
          
      - name: Run Meson install
        run: meson install -C build

      - name: Tar build and meson build
        run: tar -zcvf install.tar.gz install

      - name: Upload build dir
        uses: actions/upload-artifact@v4
        with:
          name: install
          path: install.tar.gz
