name: WINDOWS|BUILD
permissions:
  contents: read
  actions: read
  checks: none
  deployments: none
  issues: none
  discussions: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on: 
  push:
    branches:
      - main
    paths:
      - '**.hpp'
      - '**.cpp'
      - 'meson.build'
      - '.github/workflows/windows_*.yml'

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Boost
        uses: MarkusJx/install-boost@v2
        with:
          boost_version: 1.87.0
          platform_version: 2022
          toolset: msvc
          link: shared

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Meson and Ninja
        run: pip install meson ninja

      - name: Run Meson setup
        env:
          BOOST_ROOT: "${{ github.workspace }}/boost/boost"
        run: |
          $PWD=pwd
          meson setup --backend=ninja build --prefix="$PWD/install"

      - name: Run Meson install
        run: meson install -C build

      - name: Tar build and meson build
        run: tar -zcvf install.tar.gz install

      - name: Upload build dir
        uses: actions/upload-artifact@v4
        with:
          name: install
          path: install.tar.gz
