name: WINDOWS|TESTS
on: 
  workflow_run:
    workflows: [WINDOWS|BUILD]
    branches: [main]
    types: [completed]

jobs:
  tests:
    name: Tests
    runs-on: windows-latest
    steps:
      - name: Get event json
        id: get_event_json
        run: |
          $content=cat ${GITHUB_EVENT_PATH}
          content="${content//'%'/''}"
          content="${content//$'\n'/''}"
          content="${content//$'\r'/''}"
          echo "value=${content}" >> ${GITHUB_OUTPUT}

      - name: Get run id
        id: get_run_id
        run: |
          echo "value="${{ fromJson(steps.get_event_json.outputs.value).workflow_run.id }} >> ${GITHUB_OUTPUT}

      - name: Get tests binaries
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ steps.get_run_id.outputs.value }}
          name: tests
          github-token: ${{ secrets.GH_PAT }}

      - run: tar zxvf data.tar.gz
      - run: ./build/tests-details
      - run: ./build/tests-siege
